apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-serviceaccount
  namespace: vulnarena

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-ops-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets", "namespaces"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-ops-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: backend-serviceaccount
  namespace: vulnarena
roleRef:
  kind: ClusterRole
  name: backend-ops-clusterrole
  apiGroup: rbac.authorization.k8s.io
