apiVersion: v1
kind: Pod
metadata:
  name: debug-mysql
  namespace: vulnarena
spec:
  containers:
    - name: debug
      image: mysql:8.4.5
      command: [ "sleep", "3600" ]
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: mysql-pvc
