apiVersion: v1
kind: Pod
metadata:
  name: debug-pvc
  namespace: vulnarena
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: mysql-data
      mountPath: /mnt/mysql
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: mysql-pvc
